title: 'OpenLists'
description: 'Curated lists of Open Resources.'

remote_theme: hydecorp/hydejack
#remote_theme: poole/hyde

author:
  social:
    github: OpenLists
    twitter: TomDonoghue

menu:
  - title:  Data
    url:    /data/
  - title:  Software
    url:    /software/
  - title:  Spikes
    url:    /spikes/
  - title:  Python
    url:    /python/
  - title:  Git
    url:    /git/
  - title:  Math&Stats
    url:    /math/
  - title:  DSP
    url:    /dsp/
  - title:  Tasks
    url:    /tasks/
  - title:  Ontologies
    url:    /ontologies/
  - title:  Other
    url:    /other/
